apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 4
  template:
    spec:
      containers:
        - name: my-app
          image: gopikrishna0527/k8s-deploy-mulitimage-versions:3.0
          ports:
            - containerPort: 80