apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: my-app
spec: 
  selector:
  replicas: 4
  template:
    spec: 
      containers:
        - name: my-app
          image: shaikkhajaibrahim/dmttest:3.0
          ports: 
            - containerPort:  80